[toolchain]
anchor_version = "0.31.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
distin = "4xy9dYHfAzi7cAcX5JHxNR6EoMJ9PGfeQDMHx6YUQQM6"

[programs.devnet]
distin = "4xy9dYHfAzi7cAcX5JHxNR6EoMJ9PGfeQDMHx6YUQQM6"

[programs.mainnet]
distin = "4xy9dYHfAzi7cAcX5JHxNR6EoMJ9PGfeQDMHx6YUQQM6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p distin && (cd engine/tests-litesvm && cargo test)"

[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
